package mm_pb

//noinspection ALL
const (
	CGI_TYPE_DEFAULT            = 0
	CGI_TYPE_SEARCHCONTACT      = 106
	CGI_TYPE_GETMSGIMG          = 109
	CGI_TYPE_CREATECHATROOM     = 119
	CGI_TYPE_ADDCHATROOMMEMBER  = 120
	CGI_TYPE_BATCHGETHEADIMG    = 123
	CGI_TYPE_UPLOADVOICE        = 127
	CGI_TYPE_DOWNLOADVOICE      = 128
	CGI_TYPE_UPLOADMCONTACT     = 133
	CGI_TYPE_NEWGETINVITEFRIEND = 135
	CGI_TYPE_VERIFYUSER         = 137
	CGI_TYPE_NEWSYNC            = 138
	CGI_TYPE_LBSFIND            = 148
	CGI_TYPE_UPLOADVIDEO        = 149
	CGI_TYPE_GETQRCODE          = 168
	CGI_TYPE_SENDEMOJI          = 175
	CGI_TYPE_DELCHATROOMMEMBER  = 179
	CGI_TYPE_GETCONTACT         = 182
	CGI_TYPE_MASSSEND           = 193

	CGI_TYPE_MMSNSUPLOAD           = 207
	CGI_TYPE_MMSNSPORT             = 209
	CGI_TYPE_MMSNSUSERPAGE         = 212
	CGI_TYPE_MMSNSOBJECTDETAIL     = 210
	CGI_TYPE_MMSNSTIMELINE         = 211
	CGI_TYPE_MMSNSCOMMENT          = 213
	CGI_TYPE_MMSNSSYNC             = 214
	CGI_TYPE_SNSOBJECTOP           = 218
	CGI_TYPE_SENDAPPMSG            = 222
	CGI_TYPE_GETCHATROOMINFODETAIL = 223
	CGI_TYPE_GETA8KEY              = 233
	CGI_TYPE_STATUSNOTIFY          = 251
	CGI_TYPE_MMSNSTAGLIST          = 292

	CGI_TYPE_GETPROFILE = 302
	CGI_TYPE_GETCDNDNS  = 379
	CGI_TYPE_TENPAY     = 385

	CGI_TYPE_FAVSYNC            = 400
	CGI_TYPE_ADDFAVITEM         = 401
	CGI_TYPE_BATCHGETFAVITEM    = 402
	CGI_TYPE_GETFAVINFO         = 438
	CGI_TYPE_GETOPENIMRESOURCE  = 453
	CGI_TYPE_TIMESEED           = 477
	CGI_TYPE_GETPAYFUNCTIONLIST = 495

	CGI_TYPE_GETLOGINQRCODE          = 502
	CGI_TYPE_CHECKLOGINQRCODE        = 503
	CGI_TYPE_HEARTBEAT               = 518
	CGI_TYPE_GETEMOTIONDESC          = 521
	CGI_TYPE_NEWSENDMSG              = 522
	CGI_TYPE_GETONLINEINFO           = 526
	CGI_TYPE_GETCHATROOMMEMBERDETAIL = 551

	CGI_TYPE_UPLOADIMAGE         = 625
	CGI_TYPE_GETCONTACTLABELLIST = 639
	CGI_TYPE_PUSHLOGINURL        = 654
	CGI_TYPE_OPLOG               = 681

	CGI_TYPE_MANUALAUTH = 701

	CGI_TYPE_INITCONTACT = 851

	CGI_TYPE_EXTDEVICELOGINCONFIRMGET = 971
	CGI_TYPE_SETCHATROOMANNOUNCEMENT  = 993

	CGI_TYPE_ADEXPOSURE = 1231
	CGI_TYPE_ADCLICK    = 1232

	CGI_TYPE_BINDQUERYNEW  = 1501
	CGI_TYPE_QRYLISTWXHB   = 1514
	CGI_TYPE_RECEIVEWXHB   = 1581
	CGI_TYPE_QRYDETAILWXHB = 1585
	CGI_TYPE_F2FQRCODE     = 1588

	CGI_TYPE_TRANSFERSETF2FFEE = 1623
	CGI_TYPE_TRANSFERQUERY     = 1628
	CGI_TYPE_GETBANNERINFO     = 1679
	CGI_TYPE_OPENWXHB          = 1685
	CGI_TYPE_WISHWXHB          = 1682
	CGI_TYPE_TRANSFEROPERATION = 1691

	CGI_TYPE_GETTRANSFERWORDINH = 1992
)

//noinspection ALL
type CGI_URL string

const cgiBinBasePath CGI_URL = "/cgi-bin/micromsg-bin"

//noinspection ALL
const (
	CGI_URL_GETLOGINQRCODE   CGI_URL = cgiBinBasePath + "/getloginqrcode"
	CGI_URL_CHECKLOGINQRCODE CGI_URL = cgiBinBasePath + "/checkloginqrcode"
)
