// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: get_login_qr_code_response.proto

package mm_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetLoginQRCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse              *BaseResponse          `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
	QRCode                    *QRCode                `protobuf:"bytes,2,req,name=qRCode" json:"qRCode,omitempty"`
	Uuid                      *string                `protobuf:"bytes,3,req,name=uuid" json:"uuid,omitempty"`
	CheckTime                 *uint32                `protobuf:"varint,4,req,name=checkTime" json:"checkTime,omitempty"`
	AESKey                    *AesKey                `protobuf:"bytes,5,req,name=AESKey" json:"AESKey,omitempty"`
	ExpiredTime               *uint32                `protobuf:"varint,6,req,name=expiredTime" json:"expiredTime,omitempty"`
	BlueToothBroadCastUuid    *string                `protobuf:"bytes,7,opt,name=blueToothBroadCastUuid" json:"blueToothBroadCastUuid,omitempty"`
	BlueToothBroadCastContent *SKBuiltinStringBuffer `protobuf:"bytes,8,opt,name=blueToothBroadCastContent" json:"blueToothBroadCastContent,omitempty"`
}

func (x *GetLoginQRCodeResponse) Reset() {
	*x = GetLoginQRCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_login_qr_code_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLoginQRCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginQRCodeResponse) ProtoMessage() {}

func (x *GetLoginQRCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_login_qr_code_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginQRCodeResponse.ProtoReflect.Descriptor instead.
func (*GetLoginQRCodeResponse) Descriptor() ([]byte, []int) {
	return file_get_login_qr_code_response_proto_rawDescGZIP(), []int{0}
}

func (x *GetLoginQRCodeResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetLoginQRCodeResponse) GetQRCode() *QRCode {
	if x != nil {
		return x.QRCode
	}
	return nil
}

func (x *GetLoginQRCodeResponse) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *GetLoginQRCodeResponse) GetCheckTime() uint32 {
	if x != nil && x.CheckTime != nil {
		return *x.CheckTime
	}
	return 0
}

func (x *GetLoginQRCodeResponse) GetAESKey() *AesKey {
	if x != nil {
		return x.AESKey
	}
	return nil
}

func (x *GetLoginQRCodeResponse) GetExpiredTime() uint32 {
	if x != nil && x.ExpiredTime != nil {
		return *x.ExpiredTime
	}
	return 0
}

func (x *GetLoginQRCodeResponse) GetBlueToothBroadCastUuid() string {
	if x != nil && x.BlueToothBroadCastUuid != nil {
		return *x.BlueToothBroadCastUuid
	}
	return ""
}

func (x *GetLoginQRCodeResponse) GetBlueToothBroadCastContent() *SKBuiltinStringBuffer {
	if x != nil {
		return x.BlueToothBroadCastContent
	}
	return nil
}

type QRCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Len *uint32 `protobuf:"varint,1,req,name=len" json:"len,omitempty"`
	Src []byte  `protobuf:"bytes,2,req,name=src" json:"src,omitempty"`
}

func (x *QRCode) Reset() {
	*x = QRCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_login_qr_code_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QRCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRCode) ProtoMessage() {}

func (x *QRCode) ProtoReflect() protoreflect.Message {
	mi := &file_get_login_qr_code_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRCode.ProtoReflect.Descriptor instead.
func (*QRCode) Descriptor() ([]byte, []int) {
	return file_get_login_qr_code_response_proto_rawDescGZIP(), []int{1}
}

func (x *QRCode) GetLen() uint32 {
	if x != nil && x.Len != nil {
		return *x.Len
	}
	return 0
}

func (x *QRCode) GetSrc() []byte {
	if x != nil {
		return x.Src
	}
	return nil
}

var File_get_login_qr_code_response_proto protoreflect.FileDescriptor

var file_get_login_qr_code_response_proto_rawDesc = []byte{
	0x0a, 0x20, 0x67, 0x65, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x71, 0x72, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6d, 0x5f, 0x70, 0x62, 0x1a, 0x11, 0x62, 0x61, 0x73, 0x65, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x03, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x51, 0x52, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x6d, 0x6d, 0x5f, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x25, 0x0a, 0x06, 0x71, 0x52, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x6d, 0x6d, 0x5f, 0x70, 0x62, 0x2e, 0x51, 0x52, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x06, 0x71, 0x52, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x09,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x41, 0x45, 0x53,
	0x4b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x6d, 0x5f, 0x70,
	0x62, 0x2e, 0x41, 0x65, 0x73, 0x4b, 0x65, 0x79, 0x52, 0x06, 0x41, 0x45, 0x53, 0x4b, 0x65, 0x79,
	0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x36, 0x0a, 0x16, 0x62, 0x6c, 0x75, 0x65, 0x54, 0x6f, 0x6f, 0x74, 0x68, 0x42,
	0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x55, 0x75, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x16, 0x62, 0x6c, 0x75, 0x65, 0x54, 0x6f, 0x6f, 0x74, 0x68, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x5a, 0x0a, 0x19, 0x62, 0x6c,
	0x75, 0x65, 0x54, 0x6f, 0x6f, 0x74, 0x68, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x6d, 0x6d, 0x5f, 0x70, 0x62, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x52, 0x19, 0x62, 0x6c, 0x75,
	0x65, 0x54, 0x6f, 0x6f, 0x74, 0x68, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x06, 0x51, 0x52, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x03, 0x6c,
	0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52,
	0x03, 0x73, 0x72, 0x63, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x6d, 0x6d, 0x5f, 0x70, 0x62,
}

var (
	file_get_login_qr_code_response_proto_rawDescOnce sync.Once
	file_get_login_qr_code_response_proto_rawDescData = file_get_login_qr_code_response_proto_rawDesc
)

func file_get_login_qr_code_response_proto_rawDescGZIP() []byte {
	file_get_login_qr_code_response_proto_rawDescOnce.Do(func() {
		file_get_login_qr_code_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_get_login_qr_code_response_proto_rawDescData)
	})
	return file_get_login_qr_code_response_proto_rawDescData
}

var file_get_login_qr_code_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_get_login_qr_code_response_proto_goTypes = []interface{}{
	(*GetLoginQRCodeResponse)(nil), // 0: mm_pb.GetLoginQRCodeResponse
	(*QRCode)(nil),                 // 1: mm_pb.QRCode
	(*BaseResponse)(nil),           // 2: mm_pb.BaseResponse
	(*AesKey)(nil),                 // 3: mm_pb.AesKey
	(*SKBuiltinStringBuffer)(nil),  // 4: mm_pb.SKBuiltinStringBuffer
}
var file_get_login_qr_code_response_proto_depIdxs = []int32{
	2, // 0: mm_pb.GetLoginQRCodeResponse.baseResponse:type_name -> mm_pb.BaseResponse
	1, // 1: mm_pb.GetLoginQRCodeResponse.qRCode:type_name -> mm_pb.QRCode
	3, // 2: mm_pb.GetLoginQRCodeResponse.AESKey:type_name -> mm_pb.AesKey
	4, // 3: mm_pb.GetLoginQRCodeResponse.blueToothBroadCastContent:type_name -> mm_pb.SKBuiltinStringBuffer
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_get_login_qr_code_response_proto_init() }
func file_get_login_qr_code_response_proto_init() {
	if File_get_login_qr_code_response_proto != nil {
		return
	}
	file_base_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_get_login_qr_code_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLoginQRCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_login_qr_code_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QRCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_get_login_qr_code_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_login_qr_code_response_proto_goTypes,
		DependencyIndexes: file_get_login_qr_code_response_proto_depIdxs,
		MessageInfos:      file_get_login_qr_code_response_proto_msgTypes,
	}.Build()
	File_get_login_qr_code_response_proto = out.File
	file_get_login_qr_code_response_proto_rawDesc = nil
	file_get_login_qr_code_response_proto_goTypes = nil
	file_get_login_qr_code_response_proto_depIdxs = nil
}
